### PR TITLE
Rename def to setv; adjust require statements for let macro.

### PR DESCRIPTION
**Pull request by brandonwillard**
Small adjustments for recent Hy updates.

### CODE REVIEW

**Comment by brandonwillard** [comment]
I think the current problems are due to a change in the `let` macro.

Perhaps it has to do with the way in which its bindings are assigned/bound:
```elisp
=> (let [a 2 a 1] a)
_hyx_XsemicolonXletXvertical_lineX1270 = {}
_hyx_XsemicolonXletXvertical_lineX1270['a'] = 2
_hyx_XsemicolonXletXvertical_lineX1270['a']

2
=> None
```

**Comment by algernon** [comment]
The changes look fine to me. Any idea why the tests fail, and how they could be updated to work with newer Hy?

(I don't have the time to dive into it myself, sadly.)

**Comment by gilch** [comment]
That's a bug in the let macro, thanks for finding it. It looks like the binding names can only be used once. I'll fix it soon. In the meantime, you can use nested `let`s as a workaround.

```
=> (let [a 2] (let [a 1] a))
_hyx_XsemicolonXletXvertical_lineX1235 = {}
_hyx_XsemicolonXletXvertical_lineX1235['a'] = 2
_hyx_XsemicolonXletXvertical_lineX1236 = {}
_hyx_XsemicolonXletXvertical_lineX1236['a'] = 1
_hyx_XsemicolonXletXvertical_lineX1236['a']

1
```

**Comment by brandonwillard** [comment]
@gilch, thanks for the heads-up!  I created an issue for it: https://github.com/hylang/hy/issues/1645.

**Comment by algernon** [comment]
Tests look better now, thanks a lot! I'll have a bit of time this coming Friday, will look into this (and the adderall PR) then.

**Comment by brandonwillard** [comment]
All right, I think I found and corrected the remaining issues (the current &mdash; and only &mdash; test failure is something entirely different and ostensibly Python 3.3 related), but I'm also finding some aspects of Hy macros that are quite confusing.

For instance, the following doesn't work without an addition `let` require (commented out):
```clojure
=> (import [monaxhyd [monads]])
=> (require [monaxhyd.core [*]])
=> ;; (require [hy.contrib.walk [let]])
=> (domonad monads.identity-m [[a 1] [b (inc a)]] (+ a b))
from hy import HySymbol
from hy.core.language import inc
let([_hyx_XsemicolonXgXvertical_lineX1236, monads.identity_m, m_bind,
    _hyx_XsemicolonXgXvertical_lineX1236[HySymbol('m-bind')], m_result,
    _hyx_XsemicolonXgXvertical_lineX1236[HySymbol('m-result')], m_zero,
    _hyx_XsemicolonXgXvertical_lineX1236[HySymbol('m-zero')], m_plus,
    _hyx_XsemicolonXgXvertical_lineX1236[HySymbol('m-plus')]], m_bind(1, lambda
    a: m_bind(inc(a), lambda b: m_result(a + b))))

Traceback (most recent call last):
  File "/home/bwillard/projects/code/python/hy/hy/importer.py", line 199, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
NameError: name 'let' is not defined
```
It seems odd to require macros that are dependencies of imported macros, no?  Am I doing the imports incorrectly?
Regardless, I can guess that macro expansion is happening in the given context (which doesn't explicitly provide `let`), but shouldn't the `let` requirement be automatically added/inferred by `(require [monaxhyd.core [*]])`?

**Comment by brandonwillard** [comment]
I've create a PR for the remaining issue: https://github.com/hylang/hy/pull/1646

**Comment by algernon** [comment]
> It seems odd to require macros that are dependencies of imported macros, no? Am I doing the imports incorrectly?
Regardless, I can guess that macro expansion is happening in the given context (which doesn't explicitly provide `let`), but shouldn't the `let` requirement be automatically added/inferred by `(require [monaxhyd.core [*]])`?

I think you are doing the imports right, and it is a reasonable expectation that dependencies would get require'd too. But for the time being, the workaround is acceptable.

As I already merged #3, merging this too. Thank you for your work on updating monaxhyd (and adderall) to recent Hy versions!

**Comment by gilch** [comment]
@brandonwillard you should be able to put a `(require [hy.contrib.walk [let]])` in the expansion of any macro that needs it. It doesn't have to be at the top of the file.

Alternatively, you could use `macroexpand-all` to pre-expand any `let` in the expansion before you return it. I think the namespacing of macros is one area where Hy needs improvement.

**Comment by brandonwillard** [comment]
@gilch, the latter approach, with `macroexpand-all`, is exactly what I was looking for!  

Otherwise, is there an existing issue that tracks this problem/feature for `require` (if not, I can create one)?  I've found a few related issues, but nothing that directly addresses it.
Regardless, I wouldn't mind digging into this particular problem.

**Pull request merged**
